-- ms-ecommerce: esquema inicial, identico al que Hibernate creaba con
-- ddl-auto=update (nombres y tipos por omision de Hibernate 6 sobre
-- PostgreSQL) para que `validate` lo acepte y una base ya creada se pueda
-- baselinear en esta version sin tocar datos.

CREATE TABLE productos (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(255),
    imagen_url           VARCHAR(255),
    descripcion          VARCHAR(1000),
    habilidades          VARCHAR(255),
    tipo                 VARCHAR(255),
    precio_base_cop      NUMERIC(38,2),
    en_promocion         BOOLEAN,
    porcentaje_descuento INTEGER,
    fecha_fin_promocion  TIMESTAMP(6)
);

CREATE TABLE carritos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id VARCHAR(255) NOT NULL,
    total      NUMERIC(38,2)
);

CREATE TABLE items_carrito (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id      BIGINT REFERENCES carritos (id),
    producto_id     BIGINT REFERENCES productos (id),
    cantidad        INTEGER,
    precio_unitario NUMERIC(38,2),
    subtotal        NUMERIC(38,2)
);

CREATE TABLE lista_deseos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  VARCHAR(255) NOT NULL,
    producto_id BIGINT REFERENCES productos (id)
);
