-- ms-ecommerce V4 (B5): la compra es una orden con estado persistido
-- (ecommerce-carrito.yaml 1.4.0, POST /checkout y GET /ordenes).
--
-- Una orden sobrevive a un reinicio a mitad de compra: cada paso (cobro,
-- reserva de tiraje, entrega, asiento, correo) deja su marca aqui antes de
-- dar el siguiente, y una tarea programada termina las que se quedaron a
-- medias con las mismas claves de idempotencia. Por eso la tabla guarda el
-- progreso (`reservada_en`, `entregada_en`, `asiento`, `correo`), el
-- reintento (`intentos`, `proximo_intento_en`, `ultimo_error`) y quien la
-- tiene en la mano (`bloqueada_hasta`: una concesion con caducidad, para que
-- la peticion y la tarea programada nunca procesen la misma orden a la vez).
--
-- Del medio de pago SOLO la marca y los cuatro ultimos digitos: ni el numero
-- completo, ni el codigo de seguridad, ni el titular se guardan en ningun
-- sitio (7.5 pide el formulario, no conservarlo).

CREATE TABLE ordenes (
    id                   UUID PRIMARY KEY,
    usuario_id           VARCHAR(64)   NOT NULL,
    clave_idempotencia   VARCHAR(100)  NOT NULL,
    estado               VARCHAR(30)   NOT NULL,
    moneda               VARCHAR(3)    NOT NULL,
    total                NUMERIC(14,2) NOT NULL,
    tasa_de_cambio       NUMERIC(18,6),
    medio_marca          VARCHAR(20),
    medio_ultimos4       VARCHAR(4),
    referencia_pasarela  VARCHAR(64),
    motivo               VARCHAR(300),
    traza                VARCHAR(32),
    reservada_en         TIMESTAMP WITH TIME ZONE,
    entregada_en         TIMESTAMP WITH TIME ZONE,
    asiento              VARCHAR(12)   NOT NULL DEFAULT 'PENDIENTE',
    asiento_en           TIMESTAMP WITH TIME ZONE,
    correo               VARCHAR(12)   NOT NULL DEFAULT 'PENDIENTE',
    correo_en            TIMESTAMP WITH TIME ZONE,
    intentos             INTEGER       NOT NULL DEFAULT 0,
    proximo_intento_en   TIMESTAMP WITH TIME ZONE,
    ultimo_error         VARCHAR(300),
    bloqueada_hasta      TIMESTAMP WITH TIME ZONE,
    creada_en            TIMESTAMP WITH TIME ZONE NOT NULL,
    cobrada_en           TIMESTAMP WITH TIME ZONE,
    actualizada_en       TIMESTAMP WITH TIME ZONE,
    version              BIGINT        NOT NULL DEFAULT 0,
    -- La misma clave del mismo jugador es la misma compra: dos peticiones
    -- simultaneas con ella no pueden crear dos ordenes.
    CONSTRAINT ordenes_clave_por_jugador UNIQUE (usuario_id, clave_idempotencia),
    CONSTRAINT ordenes_total_positivo CHECK (total > 0)
);

CREATE INDEX ordenes_del_jugador_idx ON ordenes (usuario_id, creada_en DESC);

-- Lo que busca la tarea programada: ordenes a medias que ya toca reintentar.
CREATE INDEX ordenes_por_terminar_idx ON ordenes (proximo_intento_en)
 WHERE estado IN ('PENDIENTE', 'COBRADA', 'ENTREGADA', 'COMPENSACION_PENDIENTE', 'RECHAZADA');

CREATE TABLE lineas_orden (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id              UUID          NOT NULL REFERENCES ordenes (id),
    posicion              INTEGER       NOT NULL,
    producto_ref          VARCHAR(64)   NOT NULL,
    nombre                VARCHAR(255)  NOT NULL,
    cantidad              INTEGER       NOT NULL,
    precio_unitario       NUMERIC(14,2) NOT NULL,
    precio_original       NUMERIC(14,2) NOT NULL,
    descuento_porcentaje  INTEGER,
    subtotal              NUMERIC(14,2) NOT NULL,
    -- Cuantas unidades de esta linea ya reservo el catalogo: la reserva es de
    -- una en una, y un reintento sigue desde aqui (con las mismas claves).
    unidades_reservadas   INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT lineas_orden_posicion_unica UNIQUE (orden_id, posicion),
    CONSTRAINT lineas_orden_cantidad CHECK (cantidad BETWEEN 1 AND 20)
);
