-- ms-identidad — esquema base (R17.1, regla 8 de plataforma).
--
-- Hasta R17 este servicio no tenia Flyway: las tablas las creaba Hibernate con
-- ddl-auto=update. Este archivo es ESE esquema, volcado del DDL que Hibernate
-- genera para PostgreSQL a partir de las entidades (Usuario, PerfilUsuario,
-- TokenCredencial, DispositivoConocido, RolEntity), con nombres legibles en
-- las claves ajenas.
--
-- En una base que ya tiene estas tablas (dev en AWS), Flyway NO ejecuta este
-- archivo: con spring.flyway.baseline-on-migrate=true y baseline-version=1 lo
-- marca como linea base y solo aplica de V2 en adelante. En una base vacia
-- (banco E2E, Testcontainers) se ejecuta tal cual. MigracionesIT comprueba
-- los dos caminos contra PostgreSQL real, con ddl-auto=validate.

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(50)  NOT NULL UNIQUE,
    descripcion VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE usuarios (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id         UUID UNIQUE,
    apodo             VARCHAR(50)  NOT NULL,
    email             VARCHAR(100) NOT NULL,
    password          VARCHAR(255) NOT NULL,
    estado            VARCHAR(255) NOT NULL,
    rol_id            BIGINT       NOT NULL,
    intentos_fallidos INTEGER      NOT NULL,
    bloqueado_hasta   TIMESTAMP(6),
    suspendido_hasta  TIMESTAMP(6),
    version_token     INTEGER      NOT NULL,
    creado_en         TIMESTAMP(6),
    ultimo_acceso     TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE (apodo),
    UNIQUE (email),
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES roles (id)
);

CREATE TABLE perfiles_usuario (
    usuario_id   BIGINT       NOT NULL,
    nombres      VARCHAR(255) NOT NULL,
    apellidos    VARCHAR(255) NOT NULL,
    avatar       VARCHAR(255),
    preferencias TEXT,
    PRIMARY KEY (usuario_id),
    CONSTRAINT fk_perfiles_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE tokens_credencial (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id       BIGINT       NOT NULL,
    token            VARCHAR(64)  NOT NULL UNIQUE,
    tipo             VARCHAR(20)  NOT NULL,
    fecha_expiracion TIMESTAMP(6) NOT NULL,
    usado            BOOLEAN      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE dispositivos_conocidos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id          BIGINT       NOT NULL,
    huella              VARCHAR(64)  NOT NULL,
    fecha_primer_acceso TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dispositivos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
