spring.application.name=ms-identidad
server.port=8081

# Hilos virtuales de Java 21 conforme a la arquitectura oficial
spring.threads.virtual.enabled=true

# Formato RFC 7807 (Problem Details)
spring.mvc.problemdetails.enabled=true
