spring.datasource.url=jdbc:postgresql://localhost:5432/ms_identidad
spring.datasource.username=nexus_dev
spring.datasource.password=nexus_dev_local
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true