spring.application.name=ms-identidad
server.port=8081

# Hilos virtuales de Java 21
spring.threads.virtual.enabled=true

# Formato RFC 7807 (Problem Details)
spring.mvc.problemdetails.enabled=true

# ---------------------------------------------------------
# Configuración Oficial de Base de Datos (Documento V2)
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_identidad
spring.datasource.username=nexus_dev
spring.datasource.password=nexus_dev_local
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia de evolución de esquema bloqueada según V2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
