spring.datasource.url=jdbc:postgresql://localhost:5433/ms_identidad
spring.datasource.username=nexus_dev
spring.datasource.password=nexus_dev_local
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.seguridad.umbral-intentos-fallidos=5
app.seguridad.minutos-bloqueo=15

app.lista-negra.url=http://localhost:8086/api/v1/lista-negra/verificar

resilience4j.circuitbreaker.instances.listaNegra.sliding-window-size=10
resilience4j.circuitbreaker.instances.listaNegra.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.listaNegra.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.listaNegra.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.listaNegra.max-attempts=2
resilience4j.retry.instances.listaNegra.wait-duration=300ms

app.frontend.ruta=file:../../../frontend/app-web/src/

app.seguridad.horas-expiracion-token=24

app.auditoria.url=http://localhost:8080/api/v1/admin/auditoria/eventos
resilience4j.circuitbreaker.instances.auditoria.sliding-window-size=10
resilience4j.circuitbreaker.instances.auditoria.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.auditoria.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.auditoria.permitted-number-of-calls-in-half-open-state=3
resilience4j.retry.instances.auditoria.max-attempts=2
resilience4j.retry.instances.auditoria.wait-duration=300ms
