spring.application.name=ms-ecommerce
server.port=8090

# Configuracion de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/ecommerce_db
spring.datasource.username=ecom_user
spring.datasource.password=ecom_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate para crear/actualizar las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
