-- Base de conocimiento del chatbot (HU-CHA-004).
-- Cada fila es un "tema" reconocible por palabras clave en español y/o
-- inglés, con una respuesta ya redactada en ambos idiomas a partir de
-- contenido real del documento del proyecto (no se inventa ningún dato
-- de juego).

CREATE TABLE temas_conocimiento (
                                  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                                  categoria              VARCHAR(40)  NOT NULL,
                                  tipo_respuesta         VARCHAR(40)  NOT NULL,
                                  titulo                 VARCHAR(150) NOT NULL,
                                  palabras_clave_es      TEXT NOT NULL,
                                  palabras_clave_en      TEXT,
                                  contenido_respuesta_es TEXT NOT NULL,
                                  contenido_respuesta_en TEXT,
                                  activo                 BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_temas_conocimiento_categoria ON temas_conocimiento (categoria);
CREATE INDEX idx_temas_conocimiento_activo ON temas_conocimiento (activo);

-- =========================================================
-- Categoría: PRODUCTO
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('PRODUCTO', 'DIRECTA', 'Héroes disponibles',
                                                                                                                                                            'heroes, personajes, que heroes hay, tipos de heroe, guerrero, mago, picaro, chaman, medico, sanador, prototipos',
                                                                                                                                                            'heroes, characters, hero types, warrior, mage, rogue, shaman, medic, healer',
                                                                                                                                                            'THE NEXUS BATTLES VI tiene 8 prototipos de héroes: Guerrero Tanque (alta resistencia, poca ofensiva), Guerrero Armas (máximo daño posible, poca defensa), Mago Fuego (daño elemental alto), Mago Hielo (debilita al enemigo para asegurar la victoria), Pícaro Veneno (afecta habilidades y precisión del rival), Pícaro Machete (especialista en heridas letales), Chamán (sanador, sin capacidad ofensiva) y Médico (recuperación y apoyo con conocimientos científicos).',
                                                                                                                                                            'THE NEXUS BATTLES VI has 8 hero prototypes: Tank Warrior (high resistance, low offense), Weapons Warrior (maximum possible damage, low defense), Fire Mage (high elemental damage), Ice Mage (weakens the enemy to secure victory), Poison Rogue (affects the rival''s abilities and precision), Machete Rogue (specializes in lethal wounds), Shaman (healer, no offensive capability) and Medic (recovery and support with scientific knowledge).'),

                                                                                                                                                           ('PRODUCTO', 'DIRECTA', 'Estadísticas y nivel de un héroe',
                                                                                                                                                            'estadisticas, nivel, experiencia, subir de nivel, poder, vida, defensa, ataque, daño, stats de heroe',
                                                                                                                                                            'stats, level, experience, level up, power, health, defense, attack, damage',
                                                                                                                                                            'Cada héroe empieza en nivel 1 y puede subir hasta nivel 8; el nivel multiplica el resto de estadísticas. Las estadísticas base son: Poder (para ejecutar acciones especiales, se recupera con el tiempo), Vida (si llega a 0 el héroe muere), Defensa (reduce el daño recibido), Ataque (probabilidad de acertar un golpe) y Daño (cantidad de daño infligido al acertar). La experiencia necesaria para subir de nivel crece exponencialmente, y se gana derrotando enemigos o completando misiones.',
                                                                                                                                                            'Every hero starts at level 1 and can level up to level 8; level multiplies all other stats. The base stats are: Power (needed to use special actions, recovers over time), Health (the hero dies if it reaches 0), Defense (reduces damage taken), Attack (chance to land a hit) and Damage (amount of damage dealt on a successful hit). Experience needed to level up grows exponentially, and is earned by defeating enemies or completing missions.'),

                                                                                                                                                           ('PRODUCTO', 'DIRECTA', 'Armas, armaduras e ítems',
                                                                                                                                                            'armas, armaduras, items, equipo, equipar, gear, sets',
                                                                                                                                                            'weapons, armor, items, gear, equip',
                                                                                                                                                            'Un héroe puede equipar hasta 2 armas y hasta 2 ítems al mismo tiempo, y hasta 6 piezas de armadura (casco, pecho, guantes, brazaletes, pantalón y zapatos). Cada pieza mejora estadísticas del héroe (ataque, defensa, daño, vida) y tiene una probabilidad de caída distinta al derrotar enemigos. Una vez inicia el combate no se pueden cambiar armas ni ítems.',
                                                                                                                                                            'A hero can equip up to 2 weapons and up to 2 items at the same time, plus up to 6 armor pieces (helmet, chest, gloves, bracers, pants and boots). Each piece improves the hero''s stats (attack, defense, damage, health) and has its own drop probability when defeating enemies. Once combat starts, weapons and items can no longer be changed.'),

                                                                                                                                                           ('PRODUCTO', 'DIRECTA', 'Habilidades épicas',
                                                                                                                                                            'epicas, habilidades especiales, master, epica, como consigo una epica',
                                                                                                                                                            'epic abilities, special skills, master enemy, how to get an epic',
                                                                                                                                                            'Las habilidades épicas son mejoras especiales que no consumen "poder" y se obtienen derrotando a enemigos especiales llamados "Máster", los cuales solo aparecen en las misiones y son aleatorios (siempre con dos niveles más que el jugador). Cada tipo de héroe tiene épicas propias, con un efecto general para todos los héroes y un efecto adicional potenciado solo para el tipo de héroe correspondiente.',
                                                                                                                                                            'Epic abilities are special upgrades that don''t consume "power" and are obtained by defeating special enemies called "Master", who only appear during missions and are random (always two levels above the player). Each hero type has its own epics, with a general effect for all heroes and an extra, boosted effect only for the matching hero type.');

-- =========================================================
-- Categoría: MECANICA_JUEGO
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('MECANICA_JUEGO', 'PASO_A_PASO', 'Cómo funciona el combate por turnos',
                                                                                                                                                            'combate, turnos, como se juega, mecanica de combate, como pelear, como es una batalla',
                                                                                                                                                            'combat, turns, how to play, battle mechanics, how to fight',
                                                                                                                                                            'El juego se desarrolla por turnos, con una duración equitativa para todos los participantes: 1) El orden de turnos de la primera ronda se determina de forma aleatoria entre todos los participantes y se mantiene igual hasta el final del combate. 2) Cada jugador ejecuta una acción por turno, en la secuencia definida. 3) Las reglas de combate son las mismas sin importar si el rival es otro jugador o la inteligencia artificial. 4) La partida termina cuando solo queda un héroe o equipo activo en el campo de batalla.',
                                                                                                                                                            'The game is turn-based, with equal turn duration for every participant: 1) The turn order for the first round is determined randomly among all participants and stays the same until combat ends. 2) Each player executes one action per turn, in the defined sequence. 3) Combat rules are the same whether the opponent is another player or the AI. 4) The match ends when only one hero or team remains active on the battlefield.'),

                                                                                                                                                           ('MECANICA_JUEGO', 'DIRECTA', 'Sistema de efectos aleatorios en combate',
                                                                                                                                                            'efectos aleatorios, probabilidad de daño, critico, esquivar, tabla de efectos, como se calcula el daño',
                                                                                                                                                            'random effects, damage probability, critical hit, dodge, how is damage calculated',
                                                                                                                                                            'Cada ataque se resuelve con una tabla de control de 8000 posibilidades: según una variable aleatoria se determina si el ataque causa daño normal, daño crítico, si el enemigo lo esquiva, lo resiste o escapa del golpe, o si no causa ningún efecto. Los porcentajes base dependen del tipo de héroe (por ejemplo, un Guerrero Armas por defecto causa daño el 60% de las veces) y mejoran si el héroe lleva armas, armaduras o ítems con bonos de crítico o esquive.',
                                                                                                                                                            'Every attack is resolved using a control table of 8000 possibilities: a random variable determines whether the attack deals normal damage, critical damage, is dodged, resisted, or has no effect at all. Base percentages depend on the hero type (for example, a Weapons Warrior deals damage 60% of the time by default) and improve with weapons, armor or items that grant critical hit or dodge bonuses.');

-- =========================================================
-- Categoría: MODALIDAD_JUEGO
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('MODALIDAD_JUEGO', 'DIRECTA', 'Modo Batalla (JcJ y cooperativo)',
                                                                                                                                                            'batalla, jcj, jugador contra jugador, pvp, duelo, modo cooperativo, jugar online',
                                                                                                                                                            'battle mode, pvp, player vs player, duel, cooperative mode, play online',
                                                                                                                                                            'En "Jugar online" puedes enfrentar a otro jugador uno contra uno, o participar en batallas cooperativas de hasta 3 jugadores por equipo (equipos de hasta 6 personajes en total). También puedes incluir oponentes controlados por inteligencia artificial. En el modo cooperativo no se puede hacer daño a los héroes de tu propio equipo, salvo que un efecto lo permita explícitamente.',
                                                                                                                                                            'In "Play online" you can face another player one-on-one, or take part in cooperative battles with up to 3 players per team (teams of up to 6 characters total). You can also include AI-controlled opponents. In cooperative mode you cannot damage your own teammates'' heroes unless an effect explicitly allows it.'),

                                                                                                                                                           ('MODALIDAD_JUEGO', 'PASO_A_PASO', 'Cómo completar una misión (modo JcE)',
                                                                                                                                                            'mision, misiones, como hacer una mision, jugador contra maquina, jugador contra entorno, pve, matricular mision',
                                                                                                                                                            'mission, missions, pve, player vs environment, how to complete a mission',
                                                                                                                                                            'Para jugar una misión: 1) Entra al tablón de misiones y revisa objetivo, jefe final y recompensa. 2) Elige el héroe que enviarás (debe tener su equipo puesto y no estar en otra misión activa). 3) Configura hasta 3 rotaciones de habilidades por prioridad, que la IA usará automáticamente. 4) Confirma el inicio: el héroe queda bloqueado (no puedes usarlo en JcJ ni en torneos) mientras dura la simulación. 5) Al terminar, recibes un reporte con las recompensas, y el héroe queda libre de nuevo. Durante la misión pueden aparecer encuentros aleatorios con enemigos "Máster".',
                                                                                                                                                            'To play a mission: 1) Open the mission board and check the objective, final boss and reward. 2) Choose the hero you''ll send (it must be fully equipped and not already in another active mission). 3) Set up to 3 priority skill rotations, which the AI will use automatically. 4) Confirm the start: the hero gets locked (unusable in PvP or tournaments) while the simulation runs. 5) When it finishes, you get a report with the rewards, and the hero is freed again. Random encounters with "Master" enemies can appear during the mission.'),

                                                                                                                                                           ('MODALIDAD_JUEGO', 'DIRECTA', 'Cómo funciona el Torneo',
                                                                                                                                                            'torneo, torneos, competencia, inscribirse a un torneo, llaves del torneo',
                                                                                                                                                            'tournament, tournaments, competition, register for tournament',
                                                                                                                                                            'El torneo se juega en equipos de hasta 6 jugadores, con una inscripción pagada en dinero real o créditos del juego. El árbol del torneo tiene una longitud de 8 encuentros; si no se completan los equipos con jugadores reales, se rellenan con equipos controlados por IA. Puedes seguir las partidas en vivo (live-stream) o revisar video-streams de justas anteriores. El equipo ganador recibe créditos y una recompensa épica única para su héroe.',
                                                                                                                                                            'The tournament is played in teams of up to 6 players, with an entry fee paid in real money or in-game credits. The tournament bracket has a length of 8 matches; if not enough real player teams sign up, AI-controlled teams fill the remaining spots. You can follow matches live (live-stream) or watch video-streams of past matches. The winning team receives credits and a unique epic reward for their hero.');

-- =========================================================
-- Categoría: CUENTA_Y_REGISTRO
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('CUENTA_Y_REGISTRO', 'PASO_A_PASO', 'Cómo crear una cuenta',
                                                                                                                                                            'registrarme, crear cuenta, registro, como me registro, nueva cuenta, quiero registrarme',
                                                                                                                                                            'register, sign up, create account, new account, how do i register',
                                                                                                                                                            'Para crear tu cuenta necesitas: 1) Tus nombres y apellidos. 2) Un correo electrónico válido. 3) Una contraseña de al menos 8 caracteres, que combine letras mayúsculas, minúsculas, números y símbolos. 4) Un apodo (no puede contener palabras ofensivas, ni nombres de celebridades, políticos, dirigentes o marcas registradas). 5) Un avatar para tu perfil. Con eso tu cuenta queda creada y podrás iniciar sesión de inmediato.',
                                                                                                                                                            'To create your account you''ll need: 1) Your first and last name. 2) A valid email address. 3) A password of at least 8 characters, combining uppercase and lowercase letters, numbers and symbols. 4) A nickname (it can''t contain offensive words, or the names of celebrities, politicians, public figures or registered trademarks). 5) An avatar for your profile. Once done, your account is created and you can log in right away.'),

                                                                                                                                                           ('CUENTA_Y_REGISTRO', 'PASO_A_PASO', 'Recuperar mi contraseña',
                                                                                                                                                            'olvide mi contraseña, recuperar contraseña, restablecer clave, no recuerdo mi clave',
                                                                                                                                                            'forgot password, reset password, recover account, i forgot my password',
                                                                                                                                                            'Para recuperar tu cuenta: 1) Ve a la opción de recuperación en la pantalla de inicio de sesión. 2) Responde las preguntas de seguridad que configuraste al registrarte. 3) Recibirás un código de verificación en tu correo electrónico registrado. 4) Ingresa el código y define una nueva contraseña (mínimo 8 caracteres, combinando letras, números y símbolos).',
                                                                                                                                                            'To recover your account: 1) Go to the recovery option on the login screen. 2) Answer the security questions you set up when registering. 3) You''ll receive a verification code at your registered email. 4) Enter the code and set a new password (at least 8 characters, combining letters, numbers and symbols).'),

                                                                                                                                                           ('CUENTA_Y_REGISTRO', 'DIRECTA', 'Gestionar mi cuenta y mi perfil',
                                                                                                                                                            'mi cuenta, mi perfil, cambiar contraseña, editar perfil, configuracion de cuenta',
                                                                                                                                                            'my account, my profile, change password, edit profile, account settings',
                                                                                                                                                            'Desde el menú "Mi Cuenta" puedes gestionar tu información personal y credenciales, cambiar tu contraseña, configurar tus preferencias del sistema, ver tus estadísticas y logros como jugador, y administrar tus suscripciones y métodos de pago.',
                                                                                                                                                            'From the "My Account" menu you can manage your personal information and credentials, change your password, configure your system preferences, view your player stats and achievements, and manage your subscriptions and payment methods.');

-- =========================================================
-- Categoría: SUBASTA_Y_COMERCIO
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('SUBASTA_Y_COMERCIO', 'PASO_A_PASO', 'Cómo publicar un producto en subasta',
                                                                                                                                                            'subasta, subastas, como subastar, vender un producto, publicar en subasta, poner algo en venta',
                                                                                                                                                            'auction, auctions, how to auction, sell an item, list an item',
                                                                                                                                                            'Para publicar un producto en subasta: 1) Elige el ítem de tu inventario que quieres subastar (debe ser tuyo y no estar en uso). 2) Configura la duración (24 horas por 1 crédito de comisión, o 48 horas por 3 créditos) y el precio mínimo de puja; opcionalmente puedes fijar un precio de compra inmediata. 3) Confirma: la comisión se cobra de inmediato, se venda o no el producto, y este queda bloqueado temporalmente en tu inventario. 4) El producto queda visible en el listado de subastas activas y empieza el contador de tiempo.',
                                                                                                                                                            'To list an item for auction: 1) Choose the item from your inventory you want to auction (it must be yours and not currently in use). 2) Set the duration (24 hours for a 1-credit fee, or 48 hours for a 3-credit fee) and the minimum bid price; you can optionally set a buy-now price. 3) Confirm: the fee is charged immediately, whether the item sells or not, and the item is temporarily locked in your inventory. 4) The item becomes visible in the active auctions listing and the countdown starts.'),

                                                                                                                                                           ('SUBASTA_Y_COMERCIO', 'PASO_A_PASO', 'Cómo pujar o comprar en una subasta',
                                                                                                                                                            'pujar, puja, ofertar, comprar en subasta, compra inmediata, como ofertar por un producto',
                                                                                                                                                            'bid, bidding, buy now, purchase auction, instant buy',
                                                                                                                                                            'Para pujar necesitas estar autenticado y tener créditos suficientes: haz una oferta superior a la puja actual respetando el incremento mínimo; tus créditos quedan reservados temporalmente y se liberan si otro jugador supera tu oferta. Si el producto tiene precio de compra inmediata, cualquier comprador puede adquirirlo al instante por ese valor, y la subasta se cierra automáticamente notificando a quienes ya habían pujado.',
                                                                                                                                                            'To bid you must be logged in and have enough credits: place an offer higher than the current bid, respecting the minimum increment; your credits are temporarily reserved and released if another player outbids you. If the item has a buy-now price, any buyer can purchase it instantly for that amount, and the auction closes automatically, notifying anyone who had already bid.'),

                                                                                                                                                           ('SUBASTA_Y_COMERCIO', 'DIRECTA', 'Créditos y moneda del juego',
                                                                                                                                                            'creditos, moneda del juego, como consigo creditos, dinero del juego, moneda virtual',
                                                                                                                                                            'credits, game currency, how do i get credits, virtual currency',
                                                                                                                                                            'Los créditos son la moneda virtual del juego: se obtienen ganando batallas y misiones, y se usan para transacciones entre jugadores dentro del sistema de subastas. No tienen valor de cambio en dinero real. El dinero real solo se usa para adquirir productos publicados directamente por UPB-COMPANY a través del usuario especial "Maestro de Juego".',
                                                                                                                                                            'Credits are the game''s virtual currency: earned by winning battles and missions, and used for transactions between players within the auction system. They have no real-money exchange value. Real money is only used to buy items published directly by UPB-COMPANY through the special "Game Master" user.');

-- =========================================================
-- Categoría: SOPORTE_TECNICO
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
  ('SOPORTE_TECNICO', 'CONTEXTUAL', 'Problema técnico general',
   'no puedo entrar, error, problema tecnico, no funciona, bug, fallo, se cerro la app, no carga',
   'cannot log in, error, technical problem, does not work, bug, app crashed, not loading',
   'Cuéntame con el mayor detalle posible qué error ves o qué está fallando (por ejemplo, en qué pantalla ocurre y qué mensaje aparece). Si no logro resolverlo con la información disponible, te pondré en contacto con soporte humano y registraré tu consulta para mejorar mis respuestas.',
   'Tell me in as much detail as possible what error you''re seeing or what''s failing (for example, on which screen it happens and what message appears). If I can''t solve it with the information available, I''ll connect you with human support and log your question to improve my future answers.');

-- =========================================================
-- Categoría: POLITICAS_Y_TERMINOS
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('POLITICAS_Y_TERMINOS', 'DIRECTA', 'Sistema de sanciones',
                                                                                                                                                            'sancion, sanciones, baneo, suspension, reglas de conducta, me suspendieron, me banearon',
                                                                                                                                                            'sanctions, ban, suspension, code of conduct, i was banned, i was suspended',
                                                                                                                                                            'El sistema aplica sanciones graduales: 1) Advertencia por violar las políticas de uso. 2) Suspensión temporal (horas, días o semanas), durante la cual no puedes acceder al sistema pero tu inventario y progreso se mantienen intactos. 3) Baneo definitivo, que inhabilita la cuenta de forma permanente. Las causales incluyen lenguaje ofensivo, acoso, fraude, uso de trampas, suplantación de identidad y violación de los términos del servicio.',
                                                                                                                                                            'The system applies gradual sanctions: 1) A warning for violating usage policies. 2) A temporary suspension (hours, days or weeks), during which you can''t access the system but your inventory and progress remain intact. 3) A permanent ban, which permanently disables the account. Causes include offensive language, harassment, fraud, cheating, identity impersonation and violation of the terms of service.'),

                                                                                                                                                           ('POLITICAS_Y_TERMINOS', 'PASO_A_PASO', 'Cómo apelar una sanción',
                                                                                                                                                            'apelar, apelacion, como apelo una sancion, recurrir sancion, no estoy de acuerdo con mi baneo',
                                                                                                                                                            'appeal, how to appeal a ban, dispute a suspension',
                                                                                                                                                            'Si no estás de acuerdo con una sanción puedes apelar: 1) Abre un ticket de soporte explicando tu caso. 2) Tu apelación será revisada por un panel de moderadores o administradores. 3) Tienes un plazo de 30 días para presentar la apelación desde que se aplicó la sanción. 4) Recibirás la notificación de la decisión final en un plazo de 15 días hábiles.',
                                                                                                                                                            'If you disagree with a sanction, you can appeal: 1) Open a support ticket explaining your case. 2) Your appeal will be reviewed by a panel of moderators or administrators. 3) You have 30 days to submit the appeal from when the sanction was applied. 4) You''ll receive the final decision within 15 business days.');

-- =========================================================
-- Categoría: FAQ_GENERAL
-- =========================================================

INSERT INTO temas_conocimiento (categoria, tipo_respuesta, titulo, palabras_clave_es, palabras_clave_en, contenido_respuesta_es, contenido_respuesta_en) VALUES
                                                                                                                                                           ('FAQ_GENERAL', 'DIRECTA', 'Saludo',
                                                                                                                                                            'hola, buenas, hey, saludos, buenos dias, buenas tardes, buenas noches, que tal',
                                                                                                                                                            'hello, hi, hey, good morning, good afternoon, good evening',
                                                                                                                                                            '¡Hola! Soy el asistente virtual de THE NEXUS BATTLES VI. Puedo ayudarte con información sobre héroes y productos, mecánicas del juego, misiones, torneos, subastas, tu cuenta o problemas técnicos. ¿En qué te ayudo?',
                                                                                                                                                            'Hello! I''m the virtual assistant for THE NEXUS BATTLES VI. I can help you with information about heroes and items, game mechanics, missions, tournaments, auctions, your account, or technical issues. How can I help you?'),

                                                                                                                                                           ('FAQ_GENERAL', 'DIRECTA', 'Despedida',
                                                                                                                                                            'adios, chao, hasta luego, gracias, nos vemos, muchas gracias',
                                                                                                                                                            'bye, goodbye, thanks, thank you, see you',
                                                                                                                                                            '¡Hasta pronto! Que tengas una gran partida en THE NEXUS BATTLES VI.',
                                                                                                                                                            'See you soon! Have a great match in THE NEXUS BATTLES VI.'),

                                                                                                                                                           ('FAQ_GENERAL', 'DIRECTA', 'Qué es THE NEXUS BATTLES VI',
                                                                                                                                                            'de que trata el juego, que es nexus battles, descripcion del juego, sobre el juego, de que trata',
                                                                                                                                                            'what is this game, about the game, game description, what is nexus battles',
                                                                                                                                                            'THE NEXUS BATTLES VI "Return of the Warriors" es un juego de rol por turnos de inmersión profunda: asumes el rol de un héroe o comandante con el que forjarás tu destino, enfrentándote en misiones y batallas contra otros jugadores o contra la máquina para obtener recompensas y mejorar tus estadísticas.',
                                                                                                                                                            'THE NEXUS BATTLES VI "Return of the Warriors" is a deeply immersive turn-based role-playing game: you take on the role of a hero or commander who will forge their destiny, taking part in missions and battles against other players or the machine to earn rewards and improve your stats.');
